[package]
name = "website"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", features = ["ws"] }
maud = "0.27.0"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6", features = ["fs"] }
